---
collections:
  - name: davidban77.gns3
    source: https://galaxy.ansible.com

  - name: netbox.netbox
    source: https://galaxy.ansible.com

  - name: freeipa.ansible_freeipa  
    source: https://galaxy.ansible.com

  - name: ovirt.ovirt
    source: https://galaxy.ansible.com
