---
collections:
  - name: davidban77.gns3
  - name: netbox.netbox
  - name: freeipa.ansible_freeipa
  - name: redhat.satellite
  - name: community.general
  - name: redhat.satellite
  - name: community.crypto
  - name: onepassword.connect
