---
collections:
  - name: davidban77.gns3

  - name: netbox.netbox

  - name: freeipa.ansible_freeipa  
    version: 0.3.1  

  - name: ovirt.ovirt

  - name: redhat.rhv

  - name: redhat.satellite

  - name: community.general

  - name: jjaswanson4.install_satellite    

  - name: jjaswanson4.configure_satellite    
