satellite_deployment_fw_ports:
    - 22/tcp
    - 80/tcp
    - 443/tcp
    - 5646/tcp
    - 5647/tcp
    - 5671/tcp
    - 5674/tcp
    - 8140/tcp
    - 9090/tcp
    - 53/udp
    - 53/tcp
    - 67/udp
    - 68/udp
    - 69/udp
