---
# handlers file for sage905.mineos
- name: Reload initctl
  become: true
  command: initctl reload-configuration

- name: Restart mineos
  become: true
  service: 
    name: mineos 
    state: restarted

- name: restart_sssd
  become: true
  service:
    name: sssd
    state: restarted