---
- name: Add vmhgfs module (RHEL 6).
  template:
    src: vmhgfs.modules.j2
    dest: /etc/sysconfig/modules/vmhgfs.modules
    mode: 0755
  when: ansible_distribution_major_version|int <= 6

- name: Install open-vm-tools.
  yum:
    name: open-vm-tools
    state: present
  when: ansible_distribution_major_version|int >= 7

- include_tasks: vmware-tools.yml
  when: ansible_distribution_major_version|int <= 6
