---
- name: Create Build Host in Satellite
  hosts: localhost
  connection: localhost

  tasks:
    - name: Build Host
      redhat.satellite.host:
        architecture: x86_64
        build: true
        comment: "RHEL 8 Template"
        compute_profile: "3-Large"
        compute_resource: "Home Lab"
        compute_attributes:
          cpus: 4
          memory_mb: 4096
        content_view: "RHEL8"
        domain: "sandbox.toal.ca"
        enabled: true
        hostgroup: "Lab RHEL Hosts/RHEL 8"
        kickstart_repository:
        lifecycle_environment: "Library"
        location: "Lab"
        name: "rhel8build.sandbox.toal.ca"
        operatingsystem: "Red Hat 8.3"
        organization: "Toal.ca"
        password: "{{ vault_sat6_pass }}"
        server_url: "https://sat6.lab.toal.ca/"
        subnet: "192.168.16.0"
        username: "{{ vault_sat6_user }}"
