---
version: 1

build_arg_defaults:
  EE_BASE_IMAGE: 'registry.redhat.io/ansible-automation-platform-20-early-access/ee-supported-rhel8:latest'

ansible_config: '../../../.ansible.cfg'

dependencies:
  galaxy: collections/requirements.yml
  python: requirements.txt
