- name: Minecraft Systems - MineOS
  hosts: tag_mc_mineos:&tag_ansible
  become: true
  vars:
    nodejs_version: "8.x"
    mineos_repo: "https://github.com/sage905/mineos-node.git"
    mineos_version: "pam_auth"
  roles:
    - ansible-role-nodejs
    - sage905.mineos

- name: Minecraft Systems - Mark2
  hosts: tag_mc_mark2:&tag_ansible
  become: true
  roles:
    - sage905.mark2
    - sage905.waterfall
