---
- name: Prometheus
  hosts: podhost1.mgmt.toal.ca # Hard-coded for now
  become: yes
  vars:
    container_image: prom/prometheus
    container_name: prometheus
    container_state: running
    container_firewall_ports:
      - 9090/tcp
    container_run_args: >-
      -p 9090:9090
      -v /home/prometheus/etc:/etc/prometheus:Z
      -v /home/prometheus/data:/prometheus:Z
      -v /home/prometheus/console_libraries:/usr/share/prometheus/console_libraries:Z
      -v /home/prometheus/console_templates:/usr/share/prometheus/consoles:Z
  roles:
    - ikke_t.podman_container_systemd

  pre_tasks:
    - name: Directories exist
      file:
        path: '{{ item }}'
        state: directory
        owner: nobody
        group: nobody
      loop:
        - /home/prometheus/etc
        - /home/prometheus/data
        - /home/prometheus/console_libraries
        - /home/prometheus/console_template

- name: Grafana
  hosts: podhost1.mgmt.toal.ca # Hard-coded for now
  become: yes
  vars:
    container_image: grafana/grafana
    container_name: grafana
    container_state: running
    container_firewall_ports:
      - 3000/tcp
    container_run_args: >-
      -p 3000:3000
  roles:
    - ikke_t.podman_container_systemd
