- name: Reset Port
  hosts: switch01
  become_method: enable
  become: yes
  connection: network_cli
  gather_facts: no

  tasks:
   - name: Shut down port
     ios_interface:
         name: Gigabit2/0/13
         enabled: False
         state: down

   - name: Bring up port
     ios_interface:
         name: Gigabit2/0/13
         enabled: True
         state: up
