# Toal Lab Site Playbook
- name: Common Lab Machine Setup
  hosts: tag_ansible
  become: true
  roles:
    - toal-common

- name: Set Network OS from Netbox info.
  gather_facts: no
  hosts: switch01
  tasks:
    - name: Set network os type for Cisco
      set_fact: ansible_network_os="ios"
      when: "'Cisco IOS' in platforms"
   
- name: Configure infrastructure
  hosts: switch01
  become_method: enable
  connection: network_cli
  gather_facts: no

  roles:
    - toallab.infrastructure

- name: Ansible Red Demo Environment
  hosts: ansible_red
  become: false
  roles:
    - lightbulb-ansiblered-deck  

- name: Minecraft Systems - MineOS
  hosts: tag_mc_mineos:&tag_ansible
  become: true
  vars:
    nodejs_version: "8.x"
    mineos_repo: "https://github.com/sage905/mineos-node.git"
    mineos_version: "pam_auth"
  roles:
    - ansible-role-nodejs
    - sage905.mineos

- name: Minecraft Systems - Mark2
  hosts: tag_mc_mark2:&tag_ansible
  become: true
  roles:
    - sage905.mark2

