# Toal Lab Site Playbook
- name: Set up Network interfaces
  hosts: all
  gather_facts: true
  become: true

  roles:
    - name: linux-system-roles.network
      when: network_connections is defined

- name: Common Lab Machine Setup
  hosts: platform_linux,platform_fedora_linux
  become: true
  roles:
    - toal-common

- name: Set Network OS from Netbox info.
  gather_facts: no
  hosts: switch01
  tasks:
    - name: Set network os type for Cisco
      set_fact: ansible_network_os="ios"
      when: "'Cisco IOS' in platforms"

- name: Configure infrastructure
  hosts: switch01
  become_method: enable
  connection: network_cli
  gather_facts: no

  roles:
    - toallab.infrastructure

- name: Include Minecraft tasks
  import_playbook: minecraft.yml

- name: Include Gitea tasks
  import_playbook: gitea.yml

# - name: Include Pod Host
#   include: podhost.yml
