- name: Create Windows AD Server
  hosts: WinAD
  gather_facts: False
  connection: local
  become: no

  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
      
  roles:
    - oatakan.ansible-role-ovirt

- name: Configure AD Controller
  hosts: WinAD
  become: yes
    - oatakan.ansible-role-windows-ad-controller
