---
# Clean up DNS challenges for DNS provider DNSMadeEasy 
- name: Cleaning up challenge DNS entries for domains {{ ', '.join(domains) }} via DNSMadeEasy
  connection: local
  community.general.dnsmadeeasy:
    account_key: "{{ dme_account_key }}"
    account_secret: "{{ dme_account_secret }}"
    domain: "{{ item.key |regex_replace('^(?:.*\\.|)([^.]+\\.[^.]+)$', '\\1') }}"
    record_ttl: 60
    record_type: TXT
    record_name: "{{ item.key |regex_replace('^(.*)(\\.[^.]+\\.[^.]+)$', '\\1') }}" 
    record_value: "{{ item.value|first }}"
    state: absent
  run_once: True
  with_dict: "{{ acme_certificate_INTERNAL_challenge.challenge_data_dns }}"
  tags:
  - issue-tls-certs-newkey
  - issue-tls-certs
