---

- include_role:
    name: "{{ windows_powershell_upgrade_role }}"
  when: upgrade_powershell | bool

- name: run setup module
  setup:

- include_tasks: hotfix-tlsv12.yml
  when: "'Windows Server 2008' in ansible_distribution or 'Windows 7' in ansible_distribution"

- include_tasks: enable-tlsv12.yml

- include_tasks: update-agent-win2008.yml
  when: "'Windows Server 2008' in ansible_distribution or 'Windows 7' in ansible_distribution"

- include_tasks: security-update-win2012.yml
  when: "'Windows Server 2012' in ansible_distribution or 'Windows 8' in ansible_distribution"

- include_tasks: disable-auto-logon.yml

- include_role:
    name: "{{ windows_update_role }}"
  when: install_updates | bool

- include_role:
    name: "{{ ovirt_guest_agent_role }}"
  when: target_ovirt | bool and not target_qemu | bool

- include_role:
    name: "{{ virtio_role }}"
  when: target_qemu | bool or ('KubeVirt' in ansible_system_vendor | default(''))

- include_role:
    name: "{{ virtualbox_guest_additions_role }}"
  when: "'VirtualBox' in ansible_product_name"

- include_role:
    name: "{{ vmware_tools_role }}"
  when: "'VMware' in ansible_product_name"

- include_tasks: startup.yml

- include_tasks: policy.yml

- include_tasks: power.yml
  when: (ansible_os_product_type == 'workstation') | default(False)

- include_tasks: enable-rdp.yml

- include_tasks: cloudbase-init.yml
  when:
    - "'VMware' not in ansible_product_name"
    - "'VirtualBox' not in ansible_product_name"
    - ('KubeVirt' not in ansible_system_vendor | default(False))
    - ('Red Hat' not in ansible_system_vendor | default(False))
    - not target_ovirt | bool
    - not target_vagrant | bool

- block:
    - include_tasks: remove-apps-alt-2.yml

    - include_tasks: remove-onedrive.yml
  when:
    - remove_apps | bool
    - (ansible_os_product_type == 'workstation') | default(False)

- include_role:
    name: "{{ ec2_ena_driver_role }}"
  when: target_ec2 | bool

- name: run all handlers here
  meta: flush_handlers

- include_tasks: clean-up-components.yml
  when: clean_up_components | bool

- include_tasks: clean-up.yml

- include_tasks: sysprep.yml

- include_tasks: compact.yml

- include_tasks: shutdown.yml
  when: shutdown_instance | bool