---
# Ensure that virtual guests have the guest tools installed.
- block:
  - name: Guest Tools Repository
    rhsm_repository:
      name: rhel-7-server-rh-common-rpms
      state: present

  - name: Install ovirt-guest-agent on RHV Guests
    yum:
      name: ovirt-guest-agent
      state: present
    notify: Ovirt Agent Restart
  when: ansible_virtualization_type == "RHEV"


