---
# Ensure that virtual guests have the guest tools installed.
- block:
  - name: Guest Tools Repository
    rhsm_repository:
      name: rhel-7-server-rh-common-rpms
      state: present

  - name: Install ovirt-guest-agent on RHV Guests
    yum:
      name: ovirt-guest-agent
      state: present
    notify: Ovirt Agent Restart
  when: ansible_virtualization_type == "RHEV"

- name: Install katello-agent on Satellite managed systems
  yum:
    name: katello-agent
    state: present
  when: foreman is defined

- name: Install insights-client on RHEL systems
  yum:
    name: insights-client
    state: present
  when: ansible_os_family == "RedHat"

