---

- name: wait until the image is unlocked by the oVirt engine (<2.9)
  ovirt_disk_facts:
    auth: "{{ ovirt_auth }}"
    pattern: "name={% if item.1.name_prefix | default(true) %}{{ item.0.name }}_{% endif %}{{ item.1.name }}"
  until: (ovirt_disks is defined) and (ovirt_disks | length > 0) and (ovirt_disks[0].status != "locked")
  retries: 10
  delay: 3
  with_subelements:
    - "{{ nodes }}"
    - disks
    - skip_missing: yes
  when:
    - nodes is defined
    - disks_creation.results is defined
    - item.1 is defined