galaxy_info:
  author: Julio Villarreal 
  description: Role to Install Red Hat Satellite 6.X
  company: your company (optional)
  issue_tracker_url: http://github.com/juliovp01/ansible-satellite6-install
  license: MIT
  min_ansible_version: 1.6
  platforms:
  - name: EL
    versions:
    - 6
    - 7
  
  galaxy_tags:
  - satellite
  - redhat 
  - install
  - configuration
  - satellite6
