---
galaxy_info:
  author: Orcun Atakan
  description: Ansible galaxy role for building a Windows template on any cloud platform(ovirt/rhev, VMware, EC2, Azure etc.)
  role_name: windows_template_build
  company: Red Hat

  license: MIT

  min_ansible_version: 2.5

  platforms:
    - name: Windows
      versions:
        - all

  cloud_platforms:
    - amazon
    - google
    - azure
    - azure
    - vmware
    - ovirt

  galaxy_tags:
    - windows
    - ec2
    - vmware
    - azure
    - microsoft
    - rhev
    - rhv
    - ovirt
    - aws
    - cloud
    - multicloud
    - template

dependencies: []
