---
# handlers file for ansible-freeipa-client
#
- name: restart sssd
  tags:
    - sssd
    - freeipaclient
  become: true
  service:
    name=sssd
    state=restarted

- name: restart ssh
  tags:
    - sssd
    - freeipaclient
  become: true
  service:
    name=ssh
    state=restarted
