---

galaxy_info:
  description: >
    Periodicly cleans up all unused container images from host. Role
    sets up cron job based on whether podman or docker is installed.
  author: Ilkka Tengvall
  company: ITSE
  license: GPLv3

  min_ansible_version: 2.4

  platforms:
    - name: Debian
      versions:
        - all
    - name: EL
      versions:
        - 8
        - 7
    - name: Fedora
      versions:
        - all
    - name: Ubuntu
      versions:
        - all

  galaxy_tags:
    - containers
    - podman
    - docker

dependencies: []
