---

temp_directory: "{{ ansible_env.TEMP | default(default_temp_directory) }}"

unattend:
  administrator_password: "{{ local_administrator_password }}"
  local_accounts:
    - name: "{{ local_account_username }}"
      display_name: "{{ local_account_username }}"
      description: "{{ local_account_username }} user"
      group: Administrators
      password: "{{ local_account_password }}"
  settings:
    computer_name: wintemp
    time_zone: Central Standard Time
    skip_auto_activation: true

autologin_registry:
  - name: AutoAdminLogon
    data: 1
  - name: DefaultUserName
    data: "{{ unattend.local_accounts[0].name }}"
  - name: DefaultPassword
    data: "{{ unattend.local_accounts[0].password }}"

win_architecture_list:
  arm_64_bit_processor: arm64
  arm_32_bit_processor: arm
  64_bit: amd64
  32_bit: x86

win_architecture: "{{ win_architecture_list[(ansible_architecture | default('64-bit'))|replace('-','_')|replace(' ','_')|lower] }}"

os_version: "{{ ansible_kernel.split('.')[0] }}.{{ ansible_kernel.split('.')[1] }}"
os_version_name: "os_{{ ansible_kernel.split('.')[0] }}_{{ ansible_kernel.split('.')[1] }}"
