---
- name: Listen for Netbox Events
  hosts: all
  sources:
    - name: Netbox Listener
      ansible.eda.webhook:
        port: 9102
        host: 0.0.0.0
  rules:
    - name: Run Template
      condition:
        all:
          - "true"
      actions:
        - print_event:
            pretty: true
