---

- name: wait until the disk is unlocked by the oVirt engine (<2.9)
  ovirt_disk_facts:
    auth: "{{ ovirt_auth }}"
    pattern: "name={{ iso_file }}"
  until: (ovirt_disks is defined) and (ovirt_disks | length > 0) and (ovirt_disks[0].status != "locked")
  retries: 10
  delay: 3
  when: iso_file is defined