---
galaxy_info:
  author:
  description: Ansible role for setting up ISC DHCPD.
  license: BSD
  min_ansible_version: 2.9
  platforms:
    - name: EL
      versions:
        - 7
    - name: Fedora
      versions:
        - 29
  galaxy_tags:
    - system
    - networking
dependencies: []
