---
# handlers file for toal-common

  - name: Ovirt Agent Restart
    service:
      name: ovirt-guest-agent
      state: restarted
    when: ansible_virtualization_type == "RHEV"

  - name: Qemu Agent Restart
    service:
      name: qemu-guest-agent
      state: restarted
    when: ansible_virtualization_type == "RHEV"