- name: create an ovirt windows template
  hosts: windows_template_base
  gather_facts: False
  connection: local
  become: no

  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
      

  roles:
    - oatakan.windows_ovirt_template
