- name: Create an ovirt windows template
  hosts: windows_template_base
  gather_facts: false
  connection: local
  become: false

  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"


  roles:
    - oatakan.windows_ovirt_template
