---
- name: Create Build Host in Satellite
  hosts: localhost
  connection: localhost

  tasks:
    - name: Build Host
      redhat.satellite.host:
        architecture: x86_64
        build: true
        comment: "RHEL 8 Template"
        compute_profile: "4c8g"
        compute_attributes:  
          start: "1"
        compute_resource: "ToalLab"
        content_view: "composite-rhel8"
        domain: "sandbox.toal.ca"
        enabled: true
        hostgroup: "RHEL8"
        lifecycle_environment: "Library"
        location: "Lab"
        name: "rhel8build.sandbox.toal.ca"
        operatingsystem: "RedHat 8.3"
        organization: "Toal.ca"
        server_url: "https://satellite1.mgmt.toal.ca/"
        subnet: "sandbox"
        username: "{{ satellite_admin_user }}"
        password: "{{ satellite_admin_pass }}"
        validate_certs: no