- name: Ensure GitLab is installed
  hosts: gitlab.lab.toal.ca
  become: true
  vars:
    gitlab_external_url: "http://gitlab.lab.toal.ca/"
    gitlab_git_data_dir: "/var/opt/gitlab/git-data"
    # gitlab_edition: "gitlab-ce"
    # gitlab_redirect_http_to_https: "false"
    # # LDAP Configuration.
    # gitlab_ldap_enabled: "true"
    # gitlab_ldap_host: "idm1.mgmt.toal.ca"
    # gitlab_ldap_port: "389"
    # gitlab_ldap_uid: "ldapauth"
    # gitlab_ldap_method: "start_tls"
    # gitlab_ldap_bind_dn: "uid=ldapauth,cn=sysaccounts,cn=etc,dc=idm,dc=toal,dc=ca"
    # gitlab_ldap_password: "growwaternapkin"
    # gitlab_ldap_base: "cn=users,cn=accounts,dc=idm,dc=toal,dc=ca"
    # # Email configuration.
    # gitlab_email_enabled: "true"
    # gitlab_email_from: "gitlab@takeflight.ca"
    # gitlab_email_display_name: "Gitlab"
    # gitlab_email_reply_to: "ptoal@takeflight.ca"
    # # SMTP Configuration
    # gitlab_smtp_enable: "true"
    # gitlab_smtp_address: "smtp.gmail.com"
    # gitlab_smtp_port: "587"
    # gitlab_smtp_user_name: "server"
    # gitlab_smtp_password: "ReJ3n_Dj9EB-j3b"
    # gitlab_smtp_domain: "takeflight.ca"
    # gitlab_smtp_authentication: "login"
    # gitlab_smtp_enable_starttls_auto: "true"
    # # gitlab_smtp_tls: "false"
    # gitlab_smtp_openssl_verify_mode: "none"
    # # gitlab_smtp_ca_path: "/etc/ssl/certs"
    # # gitlab_smtp_ca_file: "/etc/ssl/certs/ca-certificates.crt"
    # gitlab_nginx_listen_https: "false"

  roles:
    - { role: geerlingguy.gitlab }
