- name: Create Windows AD Server
  hosts: WinAD
  gather_facts: false
  connection: local
  become: false

  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"

  roles:
    - oatakan.ansible-role-ovirt

- name: Configure AD Controller
  hosts: WinAD
  become: false
    - oatakan.ansible-role-windows-ad-controller
