---

install_updates: yes
instance_wait_retry_limit: 300
instance_wait_connection_timeout: 400

# this will remove existing template with the same name
template_force: no
template_found: no

export_ovf: no

enable_auto_logon: yes

remove_vm_on_error: yes
vm_failed: no

custom_efi_enabled: no
custom_efi_path: /usr/share/edk2.git/ovmf-x64/OVMF_CODE-pure-efi.fd

qemu_second_cdrom_device_bus_type: ide
qemu_second_cdrom_device_bus_id: 3
qemu_second_cdrom_device_bus_unit: 0

virtio_iso_url: https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio/virtio-win-0.1.173-2/virtio-win.iso
winrm_enable_script_url: https://raw.githubusercontent.com/ansible/ansible/devel/examples/scripts/ConfigureRemotingForAnsible.ps1

set_network_to_private: '([Activator]::CreateInstance([Type]::GetTypeFromCLSID([Guid]"{DCB00C01-570F-4A9B-8D69-199FDBA5723B}"))).GetNetworkConnections() | % {$_.GetNetwork().SetCategory(1)}'

windows_build_role: oatakan.windows_template_build

local_administrator_password: Chang3MyP@ssw0rd21
local_account_username: ansible
local_account_password: Chang3MyP@ssw0rd21

windows_distro_name: 2019_standard_core
iso_file_name: 17763.253.190108-0006.rs5_release_svc_refresh_SERVER_EVAL_x64FRE_en-us.iso
windows_sysprep_template_folder: windows_server

vm_ansible_port: 5986
vm_ansible_winrm_transport: credssp
vm_upgrade_powershell: no

template_vm_name: windows-2019-standard-core-auto
template_vm_root_disk_size: 30
template_vm_root_disk_format: cow
template_vm_root_disk_interface: virtio
template_vm_memory: 4096
template_vm_cpu: 2
template_vm_guest_id: windows_2019x64
template_vm_efi: no
template_vm_network_name: ovirtmgmt
template_vm_ip_address: 192.168.10.95
template_vm_netmask: 255.255.255.0
template_vm_gateway: 192.168.10.254
template_vm_domain: home.ad
template_vm_dns_servers:
  - 192.168.1.254
  - 8.8.8.8

template_convert_timeout: 900
template_convert_seal: no
template_timezone: 'GMT Standard Time'

ovirt_datacenter: mydatacenter
ovirt_cluster: production
ovirt_data_domain: data_domain
ovirt_export_domain: export_domain
ovirt_iso_domain: iso_domain

os_short_names:
  2008_r2_standard: 2k8R2
  2012_r2_standard: 2k12R2
  2012_r2_datacenter: 2k12R2
  2016_standard: 2k16
  2016_standard_core: 2k16
  2019_standard: 2k19
  2019_standard_core: 2k19