---
- name: convert to template
  ovirt.ovirt.ovirt_template:
    auth: "{{ ovirt_auth }}"
    name: "{{ template.name }}"
    vm: "{{ template.name }}"
    cluster: "{{ providers.ovirt.cluster }}"
    timeout: "{{ template_convert_timeout }}"
    seal: "{{ template_convert_seal }}"
  when: template is defined