---

- name: obtain SSO token with using username/password credentials
  ovirt.ovirt.ovirt_auth:
    url: "{{ lookup('env', 'OVIRT_URL')|default(ovirt.url, true) }}"
    username: "{{ lookup('env', 'OVIRT_USERNAME')|default(ovirt.username, true) }}"
    password: "{{ lookup('env', 'OVIRT_PASSWORD')|default(ovirt.password, true) }}"
    insecure: yes

- include_tasks: preflight_check_pre29.yml
  when: ansible_version.full is version('2.9', '<')

- include_tasks: preflight_check.yml
  when: ansible_version.full is version('2.9', '>=')

# remove existing template
- block:

    - include_tasks: remove_template.yml

  when:
    - remove_template
    - template_found|bool

- include_tasks: provision.yml
  when: role_action == 'provision'