---
# MY SATELLITE ENVIRONMENT VARIABLES
# main vars
satellite_deployment_hostname_short: "sat"
satellite_deployment_hostname_full: "sat.domain.org"
satellite_deployment_admin_username: "admin"
satellite_deployment_admin_password: "123456"
satellite_deployment_organization: "ORG"
satellite_deployment_location: "BRNO"

# network
satellite_deployment_ip_address: "10.35.184.33"
satellite_deployment_network_address: "10.35.184.32"
satellite_deployment_net_prefix: "27"
satellite_deployment_gw_address: "10.35.184.62"
satellite_deployment_net_interface: "eth1"
satellite_deployment_dhcp_interface: "{{ satellite_deployment_net_interface }}"
satellite_deployment_dns_interface: "{{ satellite_deployment_net_interface }}"
satellite_deployment_dns_forwarder: "10.35.64.1"
satellite_deployment_dns_zone: "sat.domain.com"
satellite_deployment_dns_reverse_zone: "64.35.10.in-addr.arpa"
satellite_deployment_dhcp_start: "10.35.184.34"
satellite_deployment_dhcp_end: "10.35.184.61"

#satellite_deployment_plugin_ports


# install
satellite_deployment_plugin_packages:
  - "foreman-discovery-image"

# registration vars
satellite_deployment_rhn_user: "rhn_user"
satellite_deployment_rhn_password: "RhnPassW0rD"

# answers for sattelite installer
satellite_deployment_answers:
  "foreman-initial-organization": "{{ satellite_deployment_organization }}"
  "foreman-initial-location": "{{ satellite_deployment_location }}"
  "foreman-admin-username": "{{ satellite_deployment_admin_username }}"
  "foreman-admin-password": "{{ satellite_deployment_admin_password }}"
  "foreman-proxy-dns": "true"
  "foreman-proxy-dns-interface": "{{ satellite_deployment_dns_interface }}"
  "foreman-proxy-dns-zone": "{{ satellite_deployment_dns_zone }}"
  "foreman-proxy-dns-forwarders": "{{ satellite_deployment_dns_forwarder }}"
  "foreman-proxy-dns-reverse": "{{ satellite_deployment_dns_reverse_zone }}"
  "foreman-proxy-dhcp": "true"
  "foreman-proxy-dhcp-interface": "{{ satellite_deployment_dhcp_interface }}"
  "foreman-proxy-dhcp-range": "{{ satellite_deployment_dhcp_start }}
    {{ satellite_deployment_dhcp_end }}"
  "foreman-proxy-dhcp-gateway": "{{ satellite_deployment_gw_address }}"
  "foreman-proxy-dhcp-nameservers": "{{ satellite_deployment_ip_address }}"
  "foreman-proxy-tftp": "true"
  "foreman-proxy-tftp-servername": "{{ satellite_deployment_hostname_full }}"
  "foreman-proxy-puppetca": "true"
  "capsule-puppet": "true"

# configure_satellite:
satellite_deployment_manifest_path: "http://my.local.server/sat-manifest.zip"
